;=================================================
; Name: Ana Cardenas Beltran
; Email: acard079@ucr.edu
; 
; Lab: lab 6, ex 1
; Lab section: 21
; TA: David Feng
; 
;=================================================
;MAIN
;=================================================
.ORIG x3000

	LD R1, ARRAY_MAIN_PTR
	LD R6, SUB_GET_STRING
	JSRR R6
	
HALT	
;DATA
ARRAY_MAIN_PTR	.FILL ARRAY_MAIN
SUB_GET_STRING	.FILL x3200
.ORIG	 x4000
ARRAY_MAIN		.BLKW #100
;=================================================
;SUBROUTINE: SUB_GET_STRING
;PARAMETER (R1): THE SUBROUTINE HAS PROMPTED THE USER TO INPUT A STRING,
;	TERMINATED BY THE [ENTER] KEY (the "sentinel), AND HAS STORED THE 
;	RECIEVED CHARACTERS IN AN ARRAY OF CHARACTERS STARTING AT R1.
;	the array is NULL-terminated; the sentinel character is not stored.
;RETURN VALUE (R5): THE NUMBER OF NON-SENTINEL CHARACTERS READ FROM THE USER
;		R1 contains the starting address of the array unchanged.
;=================================================
.ORIG x3200
	ST R1, BACKUP_R1_3200
	ST R3, BACKUP_R3_3200
	ST R4, BACKUP_R4_3200
	;ST R5, BACKUP_R5_3200
	ST R7, BACKUP_R7_3200			;BACKING UP MY REGISTERS :)

	LEA R0, INTRO_MESSAGE			;TELLS USER TO ENTER PHRASE
	PUTS
	
	;LEA R1, SUB_ARRAY
	LD R3, ENTER_ASCII
	AND R5, R5, x0
	NOT R3, R3
	ADD R3, R3, #1
	
START_WHILE
		GETC
		OUT							;ECHO CHARACTERS
	
		ADD R4, R3, R0				;TEST IF WHAT WAS ENTERED IS ENTER
		BRnp NEXT_STEP				;IF NOT ENTER, DO NEXT STEP
		BRz END_WHILE
	NEXT_STEP
		STR R0, R1, #0				;STORE INPUT IN ARRAY
		ADD R1, R1, #1				;next in array
		ADD R5, R5, #1				;R5 WILL BE RETURNED
		ADD R4, R4, #0
		BRnp START_WHILE
	END_WHILE
		;LD R3, ENTER_ASCII
		;NOT R3, R3
		;ADD R3, R3, #1				;TAKE 2'S COMPLEMENT
		;ADD R5, R3, R0				;IF CHARACTER ENTERED WAS ENTER, RESULT WILL BE 0
		;BRnp START_WHILE		
END_START_WHILE
		AND R4, R4, x0
		LEA R0, NUM_CHARS_MESSAGE
		;PUTS
		ADD R4, R4, R5
		ADD R4, R4, #15
		ADD R4, R4, #15
		ADD R4, R4, #15
		ADD R4, R4, #3
		AND R0, R0, x0 
		ADD R0, R0, R4
		;OUT							;OUTPUT NUMBER OF CHARS THAT WERE INPUTTED
		
PRINT_STRING
	LD R0, NEWLINE_CHAR
	;OUT
	LEA R0, PRINT_MESSAGE
	PUTS
	LD R0, BACKUP_R1_3200			;LOAD ARRAY
	PUTS							;OUTPUT ARRAY
	LD R0, NEWLINE_CHAR
	OUT
END_PRINT_STRING

	LD R1, BACKUP_R1_3200	
	LD R3, BACKUP_R3_3200
	LD R4, BACKUP_R4_3200
	;LD R5, BACKUP_R5_3200
	LD R7, BACKUP_R7_3200
		
	RET
		

;DATA
BACKUP_R1_3200	.BLKW	#1
BACKUP_R3_3200	.BLKW	#1
BACKUP_R4_3200	.BLKW	#1
BACKUP_R5_3200	.BLKW	#1
BACKUP_R7_3200	.BLKW	#1
INTRO_MESSAGE	.STRINGZ "\nEnter a string ending with [ENTER] \n"
NUM_CHARS_MESSAGE	.STRINGZ "Number of characters: \n"
PRINT_MESSAGE	.STRINGZ "Printed String: \n"
NEWLINE_CHAR	.FILL	'\n'
ENTER_ASCII		.FILL	#10

;SUB_ARRAY		.BLKW	#1	;I WANT TO INCREASE SIZE OF ARRAY LATER

.END
