;=================================================
; Name: Ana Cardenas Beltran
; Email: acard079@ucr.edu
; 
; Lab: lab 3, ex 4
; Lab section: 21
; TA: David Feng
; 
;=================================================
.ORIG x3000
;------------
;INSTRUCTIONS
;------------
			;LOADING VALUES
	LD	R3, ARRAY_1			;LOADS X4000 IN R2
	LD	R1, HEX_1		;LOADS 7 IN R5
	LD R2, COUNTER			;0 IN R3
	
	DO_WHILE_LOOP
		STR R1, R3, #0
		ADD R3, R3, #1			;GOES TO NEXT MEM. LOCATION
		ADD R1, R1, R1			;DOUBLES VALUE IN R1 (2^1=2=1+1 , 2^2=4=2+2...)
		STR R1, R3, #0
		ADD R2, R2, #-1			;DECREASES COUNTER
	BRp DO_WHILE_LOOP			;DO LOOP UNTIL COUNTER=0
	END_DO_WHILE_LOOP
	
				;OUTPUTTING CHARACTERS
	LD R3, ARRAY_1			;RELOAD LOCATION
	LD R2, COUNTER			;LOADS 10 AS COUNTER

	DO_WHILE_LOOP2
		LDR R1, R3, #0		;LOAD R1 TO R3

		ADD R0, R1, #0		;GET WHATEVER VALUE IS IN R1 IN R0
		OUT					;PRINTS CHARACTER
		LD R0, NEWLINE
		OUT
		ADD R3, R3, #1		;INCREASE LOCATION IN ARRAY
		ADD R2, R2, #-1		;DECREASE COUNTER
	BRzp DO_WHILE_LOOP2		;WHILE COUNTER >0, DO WHILE LOOP
	END_DO_WHILE_LOOP2
	

HALT
;------------
;LOCAL DATA
;------------
	ARRAY_1  .FILL	x4000
	HEX_1	 .FILL  x1
	COUNTER .FILL	#10
	NEWLINE	.FILL	'\n'
;------------
;REMOTE DATA
;------------
.ORIG x4000
	ARRAY	.BLKW	#10				;TO MAKE AN ARRAY WITH 10 CHARACTERS
