;=================================================
; Name: Ana Cardenas Beltran
; Email: 
; 
; Lab: lab 4, ex 2
; Lab section: 21
; TA: David Feng
; 
;=================================================
.ORIG x3000
;------------
;INSTRUCTIONS
;------------
			;LOADING VALUES
	LD	R4, ARRAY_1			;LOADS X4000 IN R2
	LD	R5, COUNTER1		;LOADS 7 IN R5
	AND R3, R3, x0			;0 IN R3
			;LOOP TO 1-7
	DO_WHILE_LOOP
		LDR R3, R4, #0		;LOADS R4 VALUE IN R3
		ADD R4, R4, #1		;INCREMENT LOCATION
		ADD R3, R3, #1		;ADD 1 TO NUMBER BEING STORED
		STR R3, R4, #0		;STORES NUMBER IN R4
		ADD R5, R5, #-1		;DECREASE COUNTER
	BRp DO_WHILE_LOOP
	END_DO_WHILE_LOOP
			;STORE 7TH VALUE IN R2
	AND R2, R2, x0			;ZEROS R2
	ADD R2, R3, #0			;PUTS R3(7TH VALUE) IN R2
			;CONTINUE LOOP WITH 7-10
	LD R6, COUNTER2			;STORES SECONT COUNTER IN R6
	DO_WHILE_LOOP1
		LDR R3, R4, #0		;LOAD R4 IN R3
		ADD R4, R4, #1		;INCREMENT LOCATION OF ARRAY
		ADD R3, R3, #1		;ADD 1 TO NUMBER BEING STORED
		STR R3, R4, #0		;STORE THE NUMBER IN R3
		ADD R6, R6, #-1		;DECREASE COUNTER
	BRp DO_WHILE_LOOP1		;DO WHILE LOOP IF POSITIVE
	END_DO_WHILE_LOOP1
	
				;OUTPUTTING CHARACTERS
	LD R4, ARRAY_1			;RELOAD LOCATION
	LD R1, COUNTER3			;LOADS 10 AS COUNTER

	DO_WHILE_LOOP2
		AND R3, R3, x0		;ZERO OUT R3
		ADD R3, R3, R4		;COPY R4 TO R3
		;CONVERT TO ASCII
		ADD R3, R3, #15		;
		ADD R3, R3, #15		;
		ADD R3, R3, #15		;ADDS 48 BECAUSE DEC 48 = CHARACTER 0
		ADD R3, R3, #3		;
		;OUTPUT CHARACTER IN ARRAY
		ADD R0, R3, #0		;GET WHATEVER VALUE IS IN R3 IN R0
		OUT					;PRINTS CHARACTER
		LD R0, newline		;GETS NEWLINE IN R0
		OUT					;PRINTS NEWLINE (FOR SPACING)
		ADD R4, R4, #1		;INCREASE LOCATION IN ARRAY
		ADD R1, R1, #-1		;DECREASE COUNTER
	BRp DO_WHILE_LOOP2		;WHILE COUNTER >0, DO WHILE LOOP
	END_DO_WHILE_LOOP2
	;NOTE: I used r4 and made r3 zero inside the loop because I didn't want "hard code"
	;The way I did my loop, even if the values in the array weren't 0,1,2,3...
	;or values that didn't increase by +1, whatever value was in that array would be printed.
	

HALT
;------------
;LOCAL DATA
;------------
	ARRAY_1  .FILL	x4000
	COUNTER1 .FILL	#7
	COUNTER2 .FILL	#3
	COUNTER3 .FILL	#10
	newline	 .FILL '\n'
;------------
;REMOTE DATA
;------------
.ORIG x4000
	ARRAY	.BLKW	#10				;TO MAKE AN ARRAY WITH 10 CHARACTERS
