;=================================================
; Name: Ana Cardenas Beltran
; Email: acard079@ucr.edu
; 
; Lab: lab 6, ex 2
; Lab section: 21
; TA: David Feng
; 
;=================================================
;MAIN
;=================================================
.ORIG x3000

	LD R1, ARRAY_MAIN_PTR
	LD R6, SUB_GET_STRING
	JSRR R6
	LD R1, ARRAY_MAIN_PTR
	LD R6, SUB_IS_PALINDROME
	JSRR R6
	
		ADD R4, R4, #0
		BRz NOT_PAL_PRINT
		BRnp IS_PAL_PRINT
	NOT_PAL_PRINT
		LD R0, QUOT_MARKS
		OUT
		LEA R0, ISNT_PAL_STR
		PUTS
		BRnzp THE_END_MAIN
	IS_PAL_PRINT
		LD R0, QUOT_MARKS
		OUT
		LEA R0, WAS_PAL_STR
		PUTS
		BRnzp THE_END_MAIN
	
THE_END_MAIN	
HALT	
;DATA
ARRAY_MAIN_PTR	.FILL ARRAY_MAIN
SUB_GET_STRING	.FILL x3200
SUB_IS_PALINDROME .FILL x3400
WAS_PAL_STR		.STRINGZ " IS a palindrome"
ISNT_PAL_STR	.STRINGZ " IS NOT a palindrome"
QUOT_MARKS		.FILL x22
.ORIG	 x4000
ARRAY_MAIN		.BLKW #100
;=================================================
;SUBROUTINE: SUB_GET_STRING
;PARAMETER (R1): THE SUBROUTINE HAS PROMPTED THE USER TO INPUT A STRING,
;	TERMINATED BY THE [ENTER] KEY (the "sentinel), AND HAS STORED THE 
;	RECIEVED CHARACTERS IN AN ARRAY OF CHARACTERS STARTING AT R1.
;	the array is NULL-terminated; the sentinel character is not stored.
;RETURN VALUE (R5): THE NUMBER OF NON-SENTINEL CHARACTERS READ FROM THE USER
;		R1 contains the starting address of the array unchanged.
;=================================================
.ORIG x3200
	ST R1, BACKUP_R1_3200
	ST R3, BACKUP_R3_3200
	ST R4, BACKUP_R4_3200
	ST R7, BACKUP_R7_3200			;BACKING UP MY REGISTERS :)

	LEA R0, INTRO_MESSAGE			;TELLS USER TO ENTER PHRASE
	PUTS
	

	LD R3, ENTER_ASCII
	AND R5, R5, x0
	NOT R3, R3
	ADD R3, R3, #1
	
START_WHILE
		GETC
		OUT							;ECHO CHARACTERS
	
		ADD R4, R3, R0				;TEST IF WHAT WAS ENTERED IS ENTER
		BRnp NEXT_STEP				;IF NOT ENTER, DO NEXT STEP
		BRz END_WHILE
	NEXT_STEP
		STR R0, R1, #0				;STORE INPUT IN ARRAY
		ADD R1, R1, #1				;next in array
		ADD R5, R5, #1				;R5 WILL BE RETURNED
		ADD R4, R4, #0
		BRnp START_WHILE
	END_WHILE
	
END_START_WHILE
		AND R4, R4, x0
		LEA R0, NUM_CHARS_MESSAGE
		ADD R4, R4, R5
		ADD R4, R4, #15
		ADD R4, R4, #15
		ADD R4, R4, #15
		ADD R4, R4, #3
		AND R0, R0, x0 
		ADD R0, R0, R4							;OUTPUT NUMBER OF CHARS THAT WERE INPUTTED
		
PRINT_STRING
	LD R0, NEWLINE_CHAR
	LEA R0, PRINT_MESSAGE
	PUTS
	LD R0, QUOT_MARKS_3200
	OUT
	LD R0, BACKUP_R1_3200			;LOAD ARRAY
	PUTS							;OUTPUT ARRAY
	;LD R0, NEWLINE_CHAR
	;OUT
END_PRINT_STRING

	LD R1, BACKUP_R1_3200	
	LD R3, BACKUP_R3_3200
	LD R4, BACKUP_R4_3200
	LD R7, BACKUP_R7_3200
		
	RET
		

;DATA
BACKUP_R1_3200	.BLKW	#1
BACKUP_R3_3200	.BLKW	#1
BACKUP_R4_3200	.BLKW	#1
;BACKUP_R5_3200	.BLKW	#1
BACKUP_R7_3200	.BLKW	#1
INTRO_MESSAGE	.STRINGZ "\nEnter a string ending with [ENTER] \n"
NUM_CHARS_MESSAGE	.STRINGZ "Number of characters: \n"
PRINT_MESSAGE	.STRINGZ "The string "
QUOT_MARKS_3200	.FILL x22
NEWLINE_CHAR	.FILL	'\n'
ENTER_ASCII		.FILL	#10

;=========================================================================
;Subroutine: SUB_IS_PALINDROME
;PARAMETER (R1)
;PARAMETER (R5):NUM OF CHARS IN ARRAY
;POSTCONDITION: DETERMINES WETHER STRING AT R1 IS A PALINDROME OR NOT
;RETURN VALUE: R4 1 IF PALINDROME, 0 OTHERWISE
;==========================================================================
.ORIG x3400
ST R1, BACKUP_R1_3400
ST R3, BACKUP_R3_3400
ST R4, BACKUP_R4_3400
ST R7, BACKUP_R7_3400

ADD R5, R5, #-1	
		ADD R2, R1, #0		;COPY R1 TO R2
		ADD R6, R1, #0
		ADD R6, R6, R5		;R2 AND R6 HAVE MEM ADDRESSES		
DO_LOOP_3400

		LDR R0, R2, #0		;R0 AND R4 HAVE VALUES
		LDR R4, R6, #0
		
		NOT R4, R4
		ADD R4, R4, #1
		ADD R4, R4, R0
		BRz IS_PAL
		BRnp ISNT_PAL
	IS_PAL
		ADD R2, R2, #1		;INCREASE R1
		ADD R6, R6, #-1		;DECREASE R5
		BRnzp DECREASE_COUNTER
	DECREASE_COUNTER
		ADD R5, R5, #-1
		BRp DO_LOOP_3400
		BRz WAS_PAL
END_DO_LOOP_3400	
	
		ADD R5, R5, #0
		BRz WAS_PAL
		BRnp ISNT_PAL
	WAS_PAL
		AND R4, R4, x0
		ADD R4, R4, #1
		BRnzp THE_END_3400
	ISNT_PAL
		AND R4, R4, x0
		BRnzp THE_END_3400
		

LD R1, BACKUP_R1_3400
LD R3, BACKUP_R3_3400
LD R4, BACKUP_R4_3400
LD R7, BACKUP_R7_3400
THE_END_3400
RET
;DATA
BACKUP_R1_3400	.BLKW #1
BACKUP_R3_3400	.BLKW #1
BACKUP_R4_3400	.BLKW #1
BACKUP_R7_3400	.BLKW #1
COUNTER_3400	.FILL #100

NEWLINE_3400	.FILL	'\n'



.END
